#!/bin/bash

echo "🚀 Triggering Debian Repository Publish"
echo "======================================"
echo ""
echo "Since gh CLI has authentication issues, use the web interface:"
echo ""
echo "1. Go to: https://github.com/sansnom-co/k8s-tools/actions/workflows/publish-deb-repo.yml"
echo "2. Click 'Run workflow' button"
echo "3. Select 'main' branch"
echo "4. Click 'Run workflow'"
echo ""
echo "Or wait for the next build to complete, which will trigger it automatically."
echo ""
echo "📊 Check GitHub Pages status at:"
echo "https://github.com/sansnom-co/k8s-tools/settings/pages"
echo ""
echo "🌐 Once published, the repository will be available at:"
echo "https://sansnom-co.github.io/k8s-tools/"
echo ""
echo "You can check if it's live with:"
echo "curl -I https://sansnom-co.github.io/k8s-tools/"