name: Watch Build Status

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'Workflow run ID to watch (optional)'
        required: false
        type: string

jobs:
  watch_builds:
    runs-on: ubuntu-latest
    steps:
      - name: Check current builds
        run: |
          echo "## Current Build Status"
          echo ""
          
          # If specific run ID provided, check that one
          if [ -n "${{ github.event.inputs.workflow_run_id }}" ]; then
            echo "### Checking specific run: ${{ github.event.inputs.workflow_run_id }}"
            gh run view ${{ github.event.inputs.workflow_run_id }} --repo ${{ github.repository }}
          else
            echo "### Recent Workflow Runs"
            echo ""
            
            # List recent runs of the build workflow
            echo "#### Build, Scan, Package, Sign, and Release Runs:"
            gh run list --workflow=build-release.yml --repo ${{ github.repository }} --limit 5
            
            echo ""
            echo "#### Upstream Release Check Runs:"
            gh run list --workflow=check-upstream-releases.yml --repo ${{ github.repository }} --limit 5
            
            # Check if any builds are currently running
            echo ""
            echo "### Currently Running Builds"
            RUNNING_BUILDS=$(gh run list --workflow=build-release.yml --repo ${{ github.repository }} --status in_progress --json databaseId,displayTitle,createdAt --jq '.[] | "- Run #\(.databaseId): \(.displayTitle) (started \(.createdAt))"')
            
            if [ -z "$RUNNING_BUILDS" ]; then
              echo "No builds currently in progress."
            else
              echo "$RUNNING_BUILDS"
            fi
          fi
          
          echo ""
          echo "### Latest Releases"
          gh release list --repo ${{ github.repository }} --limit 3
          
          echo ""
          echo "### Upstream Versions Being Tracked"
          if gh api repos/${{ github.repository }}/contents/.last_known_versions --jq '.content' | base64 -d 2>/dev/null; then
            echo ""
          else
            echo "No upstream versions file found yet. Run the upstream checker first."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Instructions
        run: |
          echo ""
          echo "## How to Monitor Builds"
          echo ""
          echo "1. **Via GitHub UI**: Visit https://github.com/${{ github.repository }}/actions"
          echo "2. **Via GitHub CLI**:"
          echo "   - Watch a specific run: \`gh run watch <RUN_ID> --repo ${{ github.repository }}\`"
          echo "   - View logs: \`gh run view <RUN_ID> --log --repo ${{ github.repository }}\`"
          echo "3. **Trigger manual build**: Create a new release tag"
          echo "4. **Check upstream**: Run the 'Check Upstream Releases' workflow manually"